/**
 * Rule Compiler and Validator.
 * Sanitizes and validates rules generated by AI to protect runtime integrity.
 */

const SUPPORTED_OPERATORS = ['>', '<', '>=', '<=', '==', 'crossover_above', 'crossover_below'];
const SUPPORTED_INDICATORS = ['Price', 'RSI', 'SMA', 'EMA', 'MACD', 'ATR', 'VWAP'];
const SUPPORTED_PATTERNS = [
  'Three Bullish Candles',
  'Three Bearish Candles',
  'Bullish Engulfing',
  'Bearish Engulfing',
  'Doji',
  'Hammer'
];

/**
 * Validates and compiles a raw JSON rule object.
 * @param {object} rawJSON - Input rule object from AI
 * @returns {object} Compiled/sanitized executable rule
 * @throws {Error} If the rule contains illegal operations or is malformed
 */
export function compileRule(rawJSON) {
  if (!rawJSON || typeof rawJSON !== 'object') {
    throw new Error('Invalid rule structure: Rule must be a JSON object.');
  }

  const compiled = {
    id: rawJSON.id || Date.now().toString(),
    name: String(rawJSON.name || 'AI Generated Rule').trim(),
    operator: String(rawJSON.operator || 'AND').toUpperCase(),
    enabled: rawJSON.enabled !== false,
    conditions: []
  };

  if (compiled.operator !== 'AND' && compiled.operator !== 'OR' && compiled.operator !== 'NOT') {
    compiled.operator = 'AND'; // fallback default
  }

  if (!Array.isArray(rawJSON.conditions) || rawJSON.conditions.length === 0) {
    throw new Error('Invalid rule structure: "conditions" must be a non-empty array.');
  }

  rawJSON.conditions.forEach((cond, index) => {
    if (!cond || typeof cond !== 'object') {
      throw new Error(`Condition at index ${index} is not an object.`);
    }

    // Pattern condition check
    if (cond.pattern) {
      const patternName = String(cond.pattern);
      if (!SUPPORTED_PATTERNS.includes(patternName)) {
        throw new Error(`Unsupported candlestick pattern: "${patternName}".`);
      }
      compiled.conditions.push({
        type: 'pattern',
        pattern: patternName
      });
      return;
    }

    // Indicator condition check
    if (cond.indicator) {
      const indName = String(cond.indicator);
      if (!SUPPORTED_INDICATORS.includes(indName)) {
        throw new Error(`Unsupported indicator: "${indName}".`);
      }

      const op = String(cond.operator);
      if (!SUPPORTED_OPERATORS.includes(op)) {
        throw new Error(`Unsupported operator: "${op}" in indicator condition.`);
      }

      if (cond.value === undefined || cond.value === null || isNaN(Number(cond.value))) {
        throw new Error(`Invalid or missing comparison value: "${cond.value}".`);
      }

      const compiledCond = {
        type: 'indicator',
        indicator: indName,
        operator: op,
        value: Number(cond.value),
        period: cond.period ? Math.max(1, parseInt(cond.period, 10)) : 14
      };

      // Add extra parameters for advanced indicators like MACD
      if (indName === 'MACD') {
        compiledCond.fastPeriod = cond.fastPeriod ? parseInt(cond.fastPeriod, 10) : 12;
        compiledCond.slowPeriod = cond.slowPeriod ? parseInt(cond.slowPeriod, 10) : 26;
        compiledCond.signalPeriod = cond.signalPeriod ? parseInt(cond.signalPeriod, 10) : 9;
        compiledCond.targetLine = cond.targetLine || 'macd'; // 'macd', 'signal', 'histogram'
      }

      compiled.conditions.push(compiledCond);
      return;
    }

    throw new Error(`Condition at index ${index} must define either a "pattern" or an "indicator".`);
  });

  return compiled;
}
