/**
 * Rule Compiler and Validator.
 * Sanitizes and validates rules generated by AI to protect runtime integrity.
 */

const SUPPORTED_OPERATORS = ['>', '<', '>=', '<=', '==', 'crossover_above', 'crossover_below'];
const SUPPORTED_INDICATORS = ['Price', 'RSI', 'SMA', 'EMA', 'MACD', 'ATR', 'VWAP', 'Candle'];
const SUPPORTED_PATTERNS = [
  'Three Bullish Candles',
  'Three Bearish Candles',
  'Bullish Engulfing',
  'Bearish Engulfing',
  'Doji',
  'Hammer'
];

/**
 * Validates and compiles a raw JSON rule object.
 * @param {object} rawJSON - Input rule object from AI
 * @returns {object} Compiled/sanitized executable rule
 * @throws {Error} If the rule contains illegal operations or is malformed
 */
export function compileRule(rawJSON) {
  if (!rawJSON || typeof rawJSON !== 'object') {
    throw new Error('Invalid rule structure: Rule must be a JSON object.');
  }

  const compiled = {
    id: rawJSON.id || Date.now().toString(),
    name: String(rawJSON.name || 'AI Generated Rule').trim(),
    operator: String(rawJSON.operator || 'AND').toUpperCase(),
    enabled: rawJSON.enabled !== false,
    conditions: []
  };

  if (compiled.operator !== 'AND' && compiled.operator !== 'OR' && compiled.operator !== 'NOT') {
    compiled.operator = 'AND'; // fallback default
  }

  if (!Array.isArray(rawJSON.conditions) || rawJSON.conditions.length === 0) {
    throw new Error('Invalid rule structure: "conditions" must be a non-empty array.');
  }

  rawJSON.conditions.forEach((cond, index) => {
    if (!cond || typeof cond !== 'object') {
      throw new Error(`Condition at index ${index} is not an object.`);
    }

    // Pattern condition check
    if (cond.pattern) {
      const patternName = String(cond.pattern);
      if (!SUPPORTED_PATTERNS.includes(patternName)) {
        throw new Error(`Unsupported candlestick pattern: "${patternName}".`);
      }
      compiled.conditions.push({
        type: 'pattern',
        pattern: patternName
      });
      return;
    }

    // Indicator condition check
    if (cond.indicator) {
      const indName = String(cond.indicator);
      if (!SUPPORTED_INDICATORS.includes(indName)) {
        throw new Error(`Unsupported indicator: "${indName}".`);
      }

      const op = String(cond.operator);
      if (!SUPPORTED_OPERATORS.includes(op)) {
        throw new Error(`Unsupported operator: "${op}" in indicator condition.`);
      }

      let parsedValue;
      if (indName === 'Candle') {
        const validProps = ['open', 'close', 'high', 'low', 'body', 'upperWick', 'lowerWick', 'upperWickRatio', 'lowerWickRatio', 'bodyRatio', 'isBearish', 'isBullish'];
        const validValProps = ['open', 'close', 'high', 'low', 'body', 'upperWick', 'lowerWick', 'prevOpen', 'prevClose', 'prevHigh', 'prevLow'];

        if (!cond.property || !validProps.includes(cond.property)) {
          throw new Error(`Unsupported or missing property: "${cond.property}" for Candle indicator.`);
        }

        if (cond.value === undefined || cond.value === null) {
          throw new Error('Missing comparison value for Candle indicator.');
        }

        if (typeof cond.value === 'string' && validValProps.includes(cond.value)) {
          parsedValue = cond.value;
        } else {
          parsedValue = parseFloat(cond.value);
          if (isNaN(parsedValue)) {
            throw new Error(`Invalid comparison value: "${cond.value}" for Candle indicator.`);
          }
        }
      } else {
        if (cond.value === undefined || cond.value === null || isNaN(Number(cond.value))) {
          throw new Error(`Invalid or missing comparison value: "${cond.value}".`);
        }
        parsedValue = Number(cond.value);
      }

      const compiledCond = {
        type: 'indicator',
        indicator: indName,
        operator: op,
        value: parsedValue,
        period: cond.period ? Math.max(1, parseInt(cond.period, 10)) : 14
      };

      if (indName === 'Candle') {
        compiledCond.property = cond.property;
      }

      // Add extra parameters for advanced indicators like MACD
      if (indName === 'MACD') {
        compiledCond.fastPeriod = cond.fastPeriod ? parseInt(cond.fastPeriod, 10) : 12;
        compiledCond.slowPeriod = cond.slowPeriod ? parseInt(cond.slowPeriod, 10) : 26;
        compiledCond.signalPeriod = cond.signalPeriod ? parseInt(cond.signalPeriod, 10) : 9;
        compiledCond.targetLine = cond.targetLine || 'macd'; // 'macd', 'signal', 'histogram'
      }

      compiled.conditions.push(compiledCond);
      return;
    }

    throw new Error(`Condition at index ${index} must define either a "pattern" or an "indicator".`);
  });

  return compiled;
}

/**
 * Compiles a Rules DSL string into a structured JSON rule object.
 * Supporting syntax:
 * WHEN
 *   RSI < 30
 *   AND
 *   EMA9 crosses above 100
 * THEN
 *   Notify
 * @param {string} dslString 
 * @returns {object} Compiled rule configuration
 */
export function parseDSL(dslString) {
  if (!dslString || typeof dslString !== 'string') {
    throw new Error('DSL input must be a string.');
  }

  const lines = dslString
    .split('\n')
    .map(l => l.trim())
    .filter(l => l.length > 0);

  const rule = {
    id: Date.now().toString(),
    name: 'DSL Compiled Rule',
    operator: 'AND',
    enabled: true,
    conditions: []
  };

  let inWhen = false;

  for (const line of lines) {
    const upperLine = line.toUpperCase();
    if (upperLine === 'WHEN') {
      inWhen = true;
      continue;
    }
    if (upperLine === 'THEN' || upperLine.startsWith('THEN')) {
      break;
    }
    if (!inWhen) continue;

    if (upperLine === 'AND') {
      rule.operator = 'AND';
      continue;
    }
    if (upperLine === 'OR') {
      rule.operator = 'OR';
      continue;
    }
    if (upperLine === 'NOT') {
      rule.operator = 'NOT';
      continue;
    }

    // Format: IndicatorName[Period] Operator Value
    const match = line.match(/^([A-Za-z]+)(\d+)?\s*(>=|<=|>|<|==|crosses\s+above|crosses\s+below|crossover\s+above|crossover\s+below)\s*([0-9.]+)/i);
    if (match) {
      let ind = match[1];
      ind = ind.toUpperCase();
      if (ind === 'PRICE') ind = 'Price';
      else if (ind === 'RSI') ind = 'RSI';
      else if (ind === 'SMA') ind = 'SMA';
      else if (ind === 'EMA') ind = 'EMA';
      else if (ind === 'MACD') ind = 'MACD';
      else if (ind === 'ATR') ind = 'ATR';
      else if (ind === 'VWAP') ind = 'VWAP';

      const period = match[2] ? parseInt(match[2], 10) : (ind === 'RSI' ? 14 : undefined);
      let op = match[3].toLowerCase();
      if (op.includes('above')) op = 'crossover_above';
      else if (op.includes('below')) op = 'crossover_below';

      const val = parseFloat(match[4]);

      rule.conditions.push({
        indicator: ind,
        period: period,
        operator: op,
        value: val
      });
      continue;
    }

    // Format: Candlestick Pattern Name
    const patternMatch = SUPPORTED_PATTERNS.find(p => upperLine.includes(p.toUpperCase()));
    if (patternMatch) {
      rule.conditions.push({
        pattern: patternMatch
      });
      continue;
    }

    throw new Error(`DSL Syntax Error: Could not parse condition line: "${line}"`);
  }

  if (rule.conditions.length === 0) {
    throw new Error('DSL Compile Failure: No valid conditions extracted. Check syntax.');
  }

  rule.name = rule.conditions.map(c => c.pattern || `${c.indicator}${c.period || ''} ${c.operator} ${c.value}`).join(' & ');
  return rule;
}
